
server:
  port: 8888

logging:
  level:
    root: info

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/sinaif/IdeaProjects/config-repo
        health:
          repositories:
            config-repo:
              profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
