server:
  port: 7901
spring:
  application:
    name: consumer-movie-registry
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true