server:
  port: 9901
spring:
  application:
    name: microservice-comsumer-movie-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true