server:
  port: 7901
spring:
  application:
    name: consumer-movie-registry
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    instance-id: movie-consumer-registry-7901
    prefer-ip-address: true