server:
  port: 7901
spring:
  application:
    name: provider-user-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: movie-consumer-ribbon-7901
    prefer-ip-address: true