server:
  port: 7001
spring:
  application:
    # this is the default for the Eureka service ID or VIP
    name: eureka-server
  security:
    user:
      name: user
      password: passwd
  profiles:
    active: cluster2
logging:
  level:
    root: info