server:
  port: 7901

spring:
  application:
    name: consumer-movie-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: consumer-movie-feign
    prefer-ip-address: true
