server:
  port: 3333
logging:
  level:
    root: info
spring:
  application:
    name: microservice-zuul
eureka:
  client:
    service-url:
      defaultZone: http://user:passwd@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
zuul:
  ignored-services: '*'
  routes:
    user:
      path: /user/**
      serviceId: microservice-provider-user-registry